myapp/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:conversation_id>/', views.detail, name='detail'),
    # path('<int:conversation_id>/results', views.results, name='results'),
    path('<int:conversation_id>/send/', views.send, name='send'),
    path('new_conversation/', views.new_conversation, name='new_conversation')
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
]

myapp/chat/models.py
from django.db import models

# Create your models here.


class Conversation(models.Model):

    conv_name = models.CharField(max_length=200)

    # pub_date = models.DateTimeField('date published')


class Message(models.Model):

    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    text = models.CharField(max_length=400)

myapp/chat/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Conversation, Message
# Create your views here.


def index(request):
    conversation_list = Conversation.objects.all()
    output = ', '.join([c.conv_name for c in conversation_list])
    return render(request, 'conversations/index.html', {'conversation_list': conversation_list})


def detail(request, conversation_id):
    conversation = get_object_or_404(Conversation, pk=conversation_id)
    return render(request, 'conversations/detail.html', {'conversation': conversation})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})
#

def send(request, conversation_id):
    conversation = get_object_or_404(Conversation, pk=conversation_id)
    message_text = request.POST['sent_text']
    conversation.message_set.create(text=message_text)
    conversation.save()

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('chat:detail', args=(conversation.id,)))



def new_conversation(request):
    new_conv_name = request.POST['conv_name']
    new_conv = Conversation(conv_name=new_conv_name)
    new_conv.save()

    return HttpResponseRedirect(reverse('chat:index'))

myapp/chat/templates/conversations/detail.html
<h1>{{ conversation.conv_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% for message in conversation.message_set.all %}
<p>{{ message.text }}</p>
{% endfor %}

<form action="{% url 'chat:send' conversation.id %}" method="post">
    {% csrf_token %}
    <input type="text" name="sent_text" value="write here">
    <!-- <label for="message{{ forloop.counter }}">{{ message.text }}</label><br> -->
<input type="submit" value="Send">
</form>

<form action="{% url 'chat:index' %}" method="get">
    <input type="submit" value="Volver a conversaciones" />
</form>

myapp/chat/templates/conversations/index.html
{% if conversation_list %}
  <ul>
  {% for conversation in conversation_list %}
      <li><a href="/chat/{{ conversation.id }}/">{{ conversation.conv_name }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>You don't have any conversations yet</p>
{% endif %}


<form action="{% url 'chat:new_conversation' %}" method="post">
    {% csrf_token %}
    <input type="text" name="conv_name">
    <!-- <label for="message{{ forloop.counter }}">{{ message.text }}</label><br> -->
<input type="submit" value="Crear nueva conversacion">
</form>